### ISSUE TITLE
O Gerente e/ou Operador calculam o preço final de um produto após a entrega do mesmo - Fluxo Alternativo

### ISSUE THREAD

**Issue by cemgthedev** [Raposones/APS-2020.2#20]
Título: Falha no cálculo de preço final
Passos:
- Dado que a pessoa é Gerente ou Operador
- E ela solicita a operação de finalização da locação
- E o produto é calculado mas de forma errada
- Ela só visualiza o valor errado da locação

**Comment by Raposones** [comment]
fechado junto com o fluxo principal, e alterada a descrição da issue (para remeter ao valor e não ao erro por falta de produto)
